# -*- coding: utf-8 -*-
"""Simple Web Scraping with BeautifulSoup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwFo5JuIqa3-I2R-ZDeofiBSVcwrqQjZ

# **Simple Web Scraping with BeautifulSoup**

<h2 style="font-family: 'poppins'; font-weight: bold; color: Green;">👨💻 Author: Irfan Ullah Khan</h2>

[![GitHub](https://img.shields.io/badge/GitHub-Profile-blue?style=for-the-badge&logo=github)](https://github.com/programmarself)
[![Kaggle](https://img.shields.io/badge/Kaggle-Profile-blue?style=for-the-badge&logo=kaggle)](https://www.kaggle.com/programmarself)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-Profile-blue?style=for-the-badge&logo=linkedin)](https://www.linkedin.com/in/irfan-ullah-khan-4a2871208/)  

[![YouTube](https://img.shields.io/badge/YouTube-Profile-red?style=for-the-badge&logo=youtube)](https://www.youtube.com/@irfanullahkhan7748)
[![Email](https://img.shields.io/badge/Email-Contact%20Me-red?style=for-the-badge&logo=email)](mailto:programmarself@gmail.com)
[![Website](https://img.shields.io/badge/Website-Contact%20Me-red?style=for-the-badge&logo=website)](https://flowcv.me/ikm)

This project demonstrates how to scrape data from a website using BeautifulSoup.
"""

# Install BeautifulSoup and Requests
!pip install beautifulsoup4 requests

# Import libraries
import requests
from bs4 import BeautifulSoup

# URL to scrape
url = 'https://techwithwarriors.com/internship-programs/'

# Send request and parse the content
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Extract and print the title
title = soup.title.string
print('Title of the page:', title)